apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 7
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault:1.13.3
        ports:
        - containerPort: 8200
      - name: redis
        image: redis
        ports: 
        - containerPort: 8201
---
apiVersion: v1
kind: Service

metadata:
  name: vault

spec:
  type: NodePort
  selector:
    app: vault  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8200
